repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: sort-simple-yaml
        files: ^/
      - id: check-added-large-files
        args:
          - '--maxkb=16'
      - id: trailing-whitespace
        args:
          - '--markdown-linebreak-ext=md'
      - id: check-yaml
        args:
          - '--allow-multiple-documents'
  # Go specific hooks
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-build-mod
      - id: go-mod-tidy
      - id: go-test-mod
      - id: go-fmt
