FROM docker.io/library/golang:1.27.1 AS builder

WORKDIR /app

# Copy go mod and sum files
COPY ./src/go.mod ./src/go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY ./src/ ./

# Build the Go app
RUN go build -o url-finder .

FROM docker.io/library/golang:1.27.1

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@v1.25.2

# Copy the Pre-built binary file from the previous stage
COPY ./examples/ /app/examples/
COPY --from=builder /app/url-finder /app

EXPOSE 40000

CMD ["dlv", "exec", "/app/url-finder", "--headless", "--listen=:40000", "--api-version=2", "--", "/app/examples/"]
